Надо подкачаться
htmlacademy-javascript/43580-keksobooking-22 pull request #9
Opened 2021-03-04 20:43 UTC by Dovakot

2021-03-06 20:35 UTC, iksah requested changes

2021-03-06 20:35 UTC, iksah commented on js/api.js
> +};
Можно просто 
```
const getData = (onSuccess, onFail) => fetch(SERVER_URL + 'data')
    .then(...);
```
Тогда функция будет возвращать промис, который можно будет использовать при работе.

2021-03-06 20:35 UTC, iksah commented on js/api.js
> +    .then((response) => {
Лишние отступы

2021-03-06 20:35 UTC, iksah commented on js/api.js
> +const getData = (onSuccess, onFail) => {
Я бы уточнил в названии функции, какие именно данные будут получены. Как и в функции отправки данных объекта.
Если мы начнем получать или отправлять какие-то другие данные - придется переименовывать эту функцию, что потом будет сделать сложнее.

2021-03-06 20:35 UTC, iksah commented on js/api.js
> +    });
Здесь тоже можно не оборачивать функции.
```
    .then((json) => onSuccess(json))
    .catch(() => onFail());
```

2021-03-06 20:35 UTC, iksah commented on js/api.js
> +    });
И  ниже в отправке данных так же.

2021-03-07 10:20 UTC, Dovakot commented on js/api.js
> +    .then((response) => {
Линтер ругается если их не добавить

2021-03-08 10:31 UTC, iksah requested changes

2021-03-08 10:31 UTC, iksah commented on js/api.js
> +  .catch(() => onFail());
Кстати, можно ещё упростить:
```
  .then(onSuccess)
  .catch(onFail);
```

2021-03-08 10:31 UTC, iksah commented on js/api.js
> +};
Здесь стоит сделать однообразно с функцией выше - не оборачивать `fetch` в `{}`, и упростить вызов onFail

2021-03-08 10:31 UTC, iksah commented on js/filter.js
> +};
`const resetFilterForm = () => filterForm.reset();`

2021-03-08 10:31 UTC, iksah commented on js/form.js
> +  });
`  adForm.addEventListener('reset', resetAdForm);`

2021-03-08 10:31 UTC, iksah commented on js/main.js
> +  },
`() => showMessage(Templates.FAILED),`

2021-03-08 10:31 UTC, iksah commented on js/map.js
> +};
И здеcь :)

2021-03-08 10:31 UTC, iksah commented on js/api.js
> +  .catch(() => onFail());
Почему так? Потому что в прошлой варианте браузер будет создавать дополнительные анонимные функции и хранить их в памяти, что в большом приложении может привести к уменьшению производительности или утечкам памяти (и тоже проблемам с производительностью).
Кстати, ещё часто говорят перформанс, а не производительность - а по ути одно и тоже.)

2021-03-08 15:05 UTC, merged